version: '3.8'

services:
  rigs:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/petroleum
    container_name: rigs

  db:
    image: postgres:14
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petroleum
      PGDATA: /var/lib/postgresql/data/pgdata
    container_name: rigs_db