env: "local" # local dev prod
storage_path: "user=gros password=grosBerg22 dbname= sslmode=disable"
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "admin"